---
name: main

on:
  push:
    branches: [ master ]
    tags: [ "[0-9]+.[0-9]+.[0-9]+*" ]
  pull_request:
    branches: [ master ]

jobs:

  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: ../.github/actions/envsetup
        with:
          python-version: "3.8"
          os: ${{ runner.os }}
      - name: Run test suite from tox
        shell: bash
        run: tox -e lint

  tests:
    name: ${{ matrix.os }}/${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ Ubuntu, MacOS, Windows ]
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
        experimental: [ false ]
        include:
          - os: Ubuntu
            python-version: "pypy-3.7"
            experimental: false
      fail-fast: false
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - uses: ../.github/actions/envsetup
        with:
          python-version: ${{ matrix.python-version }}
          os: ${{ matrix.os }}
      - name: Run test suite from tox
        shell: bash
        run: tox -e py -- -p no:sugar -p no:warnings -q

  sucess:
    runs-on: ubuntu-latest
    needs:
    - tests
    - linters
    steps:
    - run: echo "Great success!"
