---
name: main

on:
  push:
    branches: [ master ]
    tags: [ "[0-9]+.[0-9]+.[0-9]+*" ]
  pull_request:
    branches: [ master ]

jobs:

  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/envsetup
        with:
          python-version: "3.8"
          os: ${{ runner.os }}
      - name: Run test suite from tox
        shell: bash
        run: tox -e lint

  tests:
    name: ${{ matrix.os }}/${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ Ubuntu, MacOS, Windows ]
        python-version: [ 3.7, 3.8, 3.9, "3.10" ]
        experimental: [ false ]
        include:
          - os: Ubuntu
            python-version: pypy3
            experimental: false
          - os: Ubuntu
            python-version: "3.10"
            experimental: true
            bootstrap-args: "--git https://github.com/python-poetry/poetry.git@master"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/envsetup
        with:
          python-version: ${{ matrix.python-version }}
          os: ${{ matrix.os }}

      - name: Run test suite from tox
        shell: bash
        run: tox -e py -- -p no:sugar -p no:warnings -q

  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pyenvsetup
        with:
          python-version: "3.8"
          os: ${{ matrix.os }}
      - name: Run coverage with tox
        shell: bash
        run: tox -e coverage -- -p no:sugar -p no:warnings -q

  sucess:
    runs-on: ubuntu-latest
    needs:
    - tests
    - linters
    steps:
    - run: echo "Great success!"
